### ISSUE TITLE
Reit should never work! - all verifiers

### ISSUE THREAD

**Issue by JMozes16** [JMozes16/B-RIS#47]
**Describe the bug**
if two statements are the same, the rule should fail no matter what

**To Reproduce**
1. (B∨¬R)
2. (B∨¬R)
3. select DeMorgan

**Expected behavior**
Should always fail

**Screenshots**
![image](https://user-images.githubusercontent.com/85561037/184567823-380d5da0-28d0-4e52-9e97-f9e0476da42c.png)

**Additional context**

**Comment by aryash14** [comment]
I will start working on this issue asap!

**Comment by aryash14** [comment]
I have made the pull request for this issue! I added some test units to test as well for all the verifiers.

**Comment by JMozes16** [comment]
Could you link the PR to this issue?
